# Generated by Django 5.2.9 on 2025-12-31 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('moarefi', 'Moarefi'), ('moshakhasat', 'Moshakhasat'), ('video', 'Video')], max_length=20)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('list', 'List'), ('table', 'Table'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductContentBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=240)),
                ('answer_html', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('href', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=300)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cart_href',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_catalog_href',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_catalog_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_english',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_tagline',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_download_href',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='role',
            field=models.CharField(blank=True, choices=[('hero', 'Hero'), ('gallery', 'Gallery'), ('document', 'Document')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'role'], name='product_pro_product_3478d7_idx'),
        ),
        migrations.AddField(
            model_name='productcontentblock',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='product.productmedia'),
        ),
        migrations.AddField(
            model_name='productcontentblock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='product.product'),
        ),
        migrations.AddField(
            model_name='productcontentblockitem',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productcontentblock'),
        ),
        migrations.AddField(
            model_name='productfaqitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='product.product'),
        ),
        migrations.AddField(
            model_name='productnavitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='product.product'),
        ),
        migrations.AddField(
            model_name='productspecmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_models', to='product.product'),
        ),
        migrations.AddField(
            model_name='productspecitem',
            name='spec_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_items', to='product.productspecmodel'),
        ),
        migrations.AddIndex(
            model_name='productcontentblock',
            index=models.Index(fields=['product', 'section'], name='product_pro_product_66b597_idx'),
        ),
    ]
