# Generated by Django 5.2.9 on 2025-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcontentblock_productcontentblockitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnavitem',
            name='anchor_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list', 'List'), ('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productnavitem',
            name='href',
            field=models.URLField(blank=True),
        ),
    ]
