# Generated by Django 5.2.9 on 2025-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productnavitem_anchor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='url',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/media/files/'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/media/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brochure_url',
            field=models.FileField(blank=True, upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet_url',
            field=models.FileField(blank=True, upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo_video_url',
            field=models.FileField(blank=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_catalog_href',
            field=models.FileField(blank=True, upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_video_url',
            field=models.FileField(blank=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_download_href',
            field=models.FileField(blank=True, upload_to='products/docs/'),
        ),
    ]
