# Generated by Django 5.2.9 on 2026-01-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productmedia_url_productmedia_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='applications',
            field=models.TextField(blank=True, help_text='Legacy moarefi content.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand/manufacturer.', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='brochure_url',
            field=models.FileField(blank=True, help_text='Fallback for heroCatalogHref.', upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cart_href',
            field=models.URLField(blank=True, help_text='Add-to-cart URL.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='First category is used for category/categoryHref in the API.', related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet_url',
            field=models.FileField(blank=True, help_text='Fallback for specDownloadHref.', upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='demo_video_url',
            field=models.FileField(blank=True, help_text='Fallback for heroVideo.', upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full description content.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_alt',
            field=models.CharField(blank=True, help_text='Hero image alt text.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_catalog_href',
            field=models.FileField(blank=True, help_text='Hero catalog PDF.', upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_catalog_label',
            field=models.CharField(blank=True, help_text='Label for the hero catalog link.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_english',
            field=models.CharField(blank=True, help_text='Hero English text.', max_length=240),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Hero tagline text.', max_length=240),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Hero title text.', max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='hero_video_url',
            field=models.FileField(blank=True, help_text='Hero video file.', upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlight',
            field=models.CharField(blank=True, help_text='Short highlight text.', max_length=240),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlight_html',
            field=models.TextField(blank=True, help_text='Rich highlight content.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text='Fallback for highlightHtml.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlights product in lists.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='Internal model number.', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Displayed price.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Controls ordering and publish time.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Fallback for summaryHtml.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Used in product detail URL.', max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_download_href',
            field=models.FileField(blank=True, help_text='Primary spec download file.', upload_to='products/docs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary_html',
            field=models.TextField(blank=True, help_text='Rich summary content.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_overview',
            field=models.TextField(blank=True, help_text='Legacy moshakhasat content.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Public product name.', max_length=220),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='Warranty label.', max_length=120),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list', 'List'), ('image', 'Image'), ('video', 'Video')], help_text='Rendered block type.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='body',
            field=models.TextField(blank=True, help_text='Paragraph or raw text content.'),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='media',
            field=models.ForeignKey(blank=True, help_text='Pick media for image/video blocks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='product.productmedia'),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='section',
            field=models.CharField(choices=[('moarefi', 'Moarefi'), ('moshakhasat', 'Moshakhasat'), ('video', 'Video')], help_text='Which section this block belongs to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productcontentblock',
            name='title',
            field=models.CharField(blank=True, help_text='Used by heading blocks.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productcontentblockitem',
            name='label',
            field=models.CharField(blank=True, help_text='List item label.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productcontentblockitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productcontentblockitem',
            name='value',
            field=models.CharField(blank=True, help_text='List item value.', max_length=300),
        ),
        migrations.AlterField(
            model_name='productfaqitem',
            name='answer_html',
            field=models.TextField(blank=True, help_text='FAQ answer HTML/text.'),
        ),
        migrations.AlterField(
            model_name='productfaqitem',
            name='question',
            field=models.CharField(help_text='FAQ question.', max_length=240),
        ),
        migrations.AlterField(
            model_name='productfaqitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='body',
            field=models.TextField(blank=True, help_text='Feature body text.'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='title',
            field=models.CharField(help_text='Feature title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for image/video.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, help_text='Required when media_type=video/document.', null=True, upload_to='products/media/files/'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, help_text='Required when media_type=image.', null=True, upload_to='products/media/images/'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Used for list thumbnail when media_type=image.'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', help_text='Image, video, or document.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='role',
            field=models.CharField(blank=True, choices=[('hero', 'Hero'), ('gallery', 'Gallery'), ('document', 'Document')], help_text='Hero vs gallery vs document.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='title',
            field=models.CharField(blank=True, help_text='Optional display title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productnavitem',
            name='anchor_id',
            field=models.CharField(blank=True, help_text='Anchor id used by navItems.', max_length=120),
        ),
        migrations.AlterField(
            model_name='productnavitem',
            name='href',
            field=models.URLField(blank=True, help_text='Optional anchor href like #intro.'),
        ),
        migrations.AlterField(
            model_name='productnavitem',
            name='label',
            field=models.CharField(help_text='Visible nav label.', max_length=120),
        ),
        migrations.AlterField(
            model_name='productnavitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='Specification name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='unit',
            field=models.CharField(blank=True, help_text='Optional unit.', max_length=50),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='Specification value.', max_length=300),
        ),
        migrations.AlterField(
            model_name='productspecitem',
            name='name',
            field=models.CharField(help_text='Spec name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productspecitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productspecitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Optional unit.', max_length=50),
        ),
        migrations.AlterField(
            model_name='productspecitem',
            name='value',
            field=models.CharField(help_text='Spec value.', max_length=300),
        ),
        migrations.AlterField(
            model_name='productspecmodel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls ordering.'),
        ),
        migrations.AlterField(
            model_name='productspecmodel',
            name='title',
            field=models.CharField(help_text='Spec model title.', max_length=200),
        ),
    ]
