# Generated by Django 5.2.9 on 2026-01-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_status_682180_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technical_overview',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
