# Generated by Django 5.2.9 on 2026-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productfeature_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/root-categories/'),
        ),
    ]
