# Generated by Django 5.2.9 on 2026-01-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rootcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcontentblockitem',
            name='block',
        ),
        migrations.RemoveField(
            model_name='productfaqitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productnavitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecitem',
            name='spec_model',
        ),
        migrations.RemoveField(
            model_name='productspecmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brochure_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart_href',
        ),
        migrations.RemoveField(
            model_name='product',
            name='datasheet_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='demo_video_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_catalog_href',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_catalog_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_english',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_tagline',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hero_video_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlight_html',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_download_href',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary_html',
        ),
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image (optional).', null=True, upload_to='products/hero/'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Hero video (optional).', null=True, upload_to='products/hero/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Product categories.', related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Quill rich text content.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short summary.'),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Gallery image.', upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text.', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls ordering.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='product.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductContentBlock',
        ),
        migrations.DeleteModel(
            name='ProductContentBlockItem',
        ),
        migrations.DeleteModel(
            name='ProductFaqItem',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
        migrations.DeleteModel(
            name='ProductNavItem',
        ),
        migrations.DeleteModel(
            name='ProductSpecItem',
        ),
        migrations.DeleteModel(
            name='ProductSpecModel',
        ),
        migrations.AddIndex(
            model_name='productgalleryimage',
            index=models.Index(fields=['product'], name='product_pro_product_44c832_idx'),
        ),
    ]
