# Generated by Django 5.2.9 on 2026-01-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productcontentblockitem_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='FAQ question.', max_length=240)),
                ('answer', models.TextField(blank=True, help_text='FAQ answer text/HTML.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls ordering.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='product.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
