# Generated by Django 5.2.9 on 2026-01-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productfaqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_name', models.CharField(help_text='Column title (e.g. model name).', max_length=120)),
                ('label', models.CharField(help_text='Row label.', max_length=200)),
                ('value', models.CharField(blank=True, help_text='Cell value.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls ordering.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_items', to='product.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
