# Generated by Django 5.2.9 on 2026-01-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productspecitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Other products to show as related.', related_name='related_to', to='product.product'),
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(help_text='Product video file.', upload_to='products/videos/')),
                ('title', models.CharField(blank=True, help_text='Optional video title.', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls ordering.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='product.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product'], name='product_pro_product_04f17c_idx')],
            },
        ),
    ]
