# Generated by Django 5.2.9 on 2026-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_related_products_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default='', help_text='Full Quill rich text content.'),
        ),
    ]
